import Link from "next/link";
import {
  getAvailableProjects,
  getDashboardSessions,
  resolveProject
} from "../../lib/sessions";
import { ProjectSelector } from "./project-selector";

function formatRelativeTime(value: string): string {
  const timestamp = new Date(value).getTime();

  if (Number.isNaN(timestamp)) {
    return "Unknown time";
  }

  const seconds = Math.max(0, Math.floor((Date.now() - timestamp) / 1000));
  const minutes = Math.floor(seconds / 60);
  const hours = Math.floor(minutes / 60);
  const days = Math.floor(hours / 24);

  if (seconds < 60) {
    return "Just now";
  }

  if (minutes < 60) {
    return `${minutes} ${minutes === 1 ? "minute" : "minutes"} ago`;
  }

  if (hours < 24) {
    return `${hours} ${hours === 1 ? "hour" : "hours"} ago`;
  }

  return `${days} ${days === 1 ? "day" : "days"} ago`;
}

function projectHref(path: string, projectId: string): string {
  return `${path}?project=${encodeURIComponent(projectId)}`;
}

type DashboardViewProps = {
  projectId?: string;
};

export function DashboardView({ projectId }: DashboardViewProps) {
  const project = resolveProject(projectId);
  const projects = getAvailableProjects();
  const sessions = getDashboardSessions(project.projectId);

  return (
    <main className="page">
      <div className="shell">
        <nav className="nav" aria-label="Main navigation">
          <a className="brand" href="/">
            VibeLog
          </a>
          <div className="nav-actions">
            <Link
              className="button secondary"
              href={projectHref("/dashboard/overview", project.projectId)}
            >
              Overview
            </Link>
            <Link
              className="button secondary"
              href={projectHref("/dashboard/reports", project.projectId)}
            >
              Reports
            </Link>
            <Link
              className="button secondary"
              href={projectHref("/dashboard/story", project.projectId)}
            >
              Project Story
            </Link>
            <Link
              className="button secondary"
              href={projectHref("/dashboard/settings", project.projectId)}
            >
              Settings
            </Link>
            <Link
              className="button secondary"
              href={projectHref("/dashboard/compare", project.projectId)}
            >
              Compare
            </Link>
            <Link
              className="button secondary"
              href={projectHref("/dashboard/search", project.projectId)}
            >
              Search
            </Link>
            <Link
              className="button secondary"
              href={projectHref("/dashboard/timeline", project.projectId)}
            >
              Timeline
            </Link>
            <Link
              className="button secondary"
              href={projectHref("/dashboard/readme", project.projectId)}
            >
              README Generator
            </Link>
            <Link
              className="button secondary"
              href={projectHref("/dashboard/portfolio", project.projectId)}
            >
              Portfolio Generator
            </Link>
          </div>
        </nav>

        <header className="dashboard-header dashboard-header-row">
          <div>
            <h1>VibeLog Dashboard</h1>
            <p>
              A local-first workspace for reviewing development logs generated by
              the CLI.
            </p>
            <p className="project-label">
              Current project: {project.projectName} ({project.projectId})
            </p>
            <ProjectSelector
              currentProjectId={project.projectId}
              projects={projects}
            />
          </div>
          <div className="session-count">
            <strong>{sessions.length}</strong>
            <span>{sessions.length === 1 ? "session" : "sessions"}</span>
          </div>
        </header>

        <section aria-label="Recent sessions">
          {sessions.length === 0 ? (
            <div className="empty-state">No sessions found</div>
          ) : (
            <div className="session-list">
              {sessions.map((session) => (
                <Link
                  className="session-card"
                  href={projectHref(
                    `/dashboard/session/${session.id}`,
                    project.projectId
                  )}
                  key={session.id}
                >
                  <div>
                    <h2>{session.featureName}</h2>
                    <p>{session.summary}</p>
                    {session.tags.length > 0 ? (
                      <div className="tag-list" aria-label="Session tags">
                        {session.tags.map((tag) => (
                          <span className="tag-pill" key={tag}>
                            {tag}
                          </span>
                        ))}
                      </div>
                    ) : null}
                  </div>
                  <dl className="session-meta">
                    <div>
                      <dt>Updated</dt>
                      <dd>{formatRelativeTime(session.createdAt)}</dd>
                      <dd className="small-text">{session.createdAt}</dd>
                    </div>
                    <div>
                      <dt>Changed files</dt>
                      <dd>{session.changedFilesCount}</dd>
                    </div>
                  </dl>
                </Link>
              ))}
            </div>
          )}
        </section>
      </div>
    </main>
  );
}
