const cards = [
  {
    title: "Recent Sessions",
    description: "Review locally saved coding sessions from the CLI."
  },
  {
    title: "Markdown Logs",
    description: "Browse generated Markdown development logs."
  },
  {
    title: "Portfolio Generator",
    description: "Prepare concise project stories from session summaries."
  }
];

export default function DashboardPage() {
  return (
    <main className="page">
      <div className="shell">
        <nav className="nav" aria-label="Main navigation">
          <a className="brand" href="/">
            VibeLog
          </a>
        </nav>

        <header className="dashboard-header">
          <h1>VibeLog Dashboard</h1>
          <p>
            A local-first workspace for reviewing development logs generated by
            the CLI.
          </p>
        </header>

        <section className="card-grid" aria-label="Dashboard sections">
          {cards.map((card) => (
            <article className="card" key={card.title}>
              <h2>{card.title}</h2>
              <p>{card.description}</p>
            </article>
          ))}
        </section>
      </div>
    </main>
  );
}
