import Link from "next/link";
import { getDashboardSessions } from "../../lib/sessions";

export const dynamic = "force-dynamic";

export default function DashboardPage() {
  const sessions = getDashboardSessions();

  return (
    <main className="page">
      <div className="shell">
        <nav className="nav" aria-label="Main navigation">
          <a className="brand" href="/">
            VibeLog
          </a>
        </nav>

        <header className="dashboard-header">
          <h1>VibeLog Dashboard</h1>
          <p>
            A local-first workspace for reviewing development logs generated by
            the CLI.
          </p>
        </header>

        <section aria-label="Recent sessions">
          {sessions.length === 0 ? (
            <div className="empty-state">No sessions found</div>
          ) : (
            <div className="session-list">
              {sessions.map((session) => (
                <Link
                  className="session-card"
                  href={`/dashboard/session/${session.id}`}
                  key={session.id}
                >
                  <div>
                    <h2>{session.featureName}</h2>
                    <p>{session.summary}</p>
                  </div>
                  <dl className="session-meta">
                    <div>
                      <dt>Created</dt>
                      <dd>{session.createdAt}</dd>
                    </div>
                    <div>
                      <dt>Changed files</dt>
                      <dd>{session.changedFilesCount}</dd>
                    </div>
                  </dl>
                </Link>
              ))}
            </div>
          )}
        </section>
      </div>
    </main>
  );
}
