import Link from "next/link";
import { getDashboardSessions } from "../../lib/sessions";

export const dynamic = "force-dynamic";

function formatRelativeTime(value: string): string {
  const timestamp = new Date(value).getTime();

  if (Number.isNaN(timestamp)) {
    return "Unknown time";
  }

  const seconds = Math.max(0, Math.floor((Date.now() - timestamp) / 1000));
  const minutes = Math.floor(seconds / 60);
  const hours = Math.floor(minutes / 60);
  const days = Math.floor(hours / 24);

  if (seconds < 60) {
    return "Just now";
  }

  if (minutes < 60) {
    return `${minutes} ${minutes === 1 ? "minute" : "minutes"} ago`;
  }

  if (hours < 24) {
    return `${hours} ${hours === 1 ? "hour" : "hours"} ago`;
  }

  return `${days} ${days === 1 ? "day" : "days"} ago`;
}

export default function DashboardPage() {
  const sessions = getDashboardSessions();

  return (
    <main className="page">
      <div className="shell">
        <nav className="nav" aria-label="Main navigation">
          <a className="brand" href="/">
            VibeLog
          </a>
        </nav>

        <header className="dashboard-header dashboard-header-row">
          <div>
            <h1>VibeLog Dashboard</h1>
            <p>
              A local-first workspace for reviewing development logs generated by
              the CLI.
            </p>
          </div>
          <div className="session-count">
            <strong>{sessions.length}</strong>
            <span>{sessions.length === 1 ? "session" : "sessions"}</span>
          </div>
        </header>

        <section aria-label="Recent sessions">
          {sessions.length === 0 ? (
            <div className="empty-state">No sessions found</div>
          ) : (
            <div className="session-list">
              {sessions.map((session) => (
                <Link
                  className="session-card"
                  href={`/dashboard/session/${session.id}`}
                  key={session.id}
                >
                  <div>
                    <h2>{session.featureName}</h2>
                    <p>{session.summary}</p>
                  </div>
                  <dl className="session-meta">
                    <div>
                      <dt>Updated</dt>
                      <dd>{formatRelativeTime(session.createdAt)}</dd>
                      <dd className="small-text">{session.createdAt}</dd>
                    </div>
                    <div>
                      <dt>Changed files</dt>
                      <dd>{session.changedFilesCount}</dd>
                    </div>
                  </dl>
                </Link>
              ))}
            </div>
          )}
        </section>
      </div>
    </main>
  );
}
